site_name: Codeforces Solutions
site_description: codeforces solutions
site_author: Girish Thatte
site_url: https://girishgr8.github.io

nav:
  - Introduction: index.md
  - Standard Problems:
      - Dynamic Programming:
          - "0/1 Knapsack": dp/01knapsack.md
          - "Longest Common Subsequence(LCS)": dp/longestcommonnsubsequence.md
          - "Longest Common Substring": dp/longestcommonsubstring.md
          - "Longest Increasing Subsequence(LIS)": dp/longestincreasingsubsequence.md
          - "Longest Palindromic Subsequence(LPS)": dp/longestpalindromicsubsequence.md
          - "Coin Change - minimum number of coins to make the change": dp/mincoinchange.md

  - Codeforces Problems:
      - 1475:
          - A. Odd Divisor: problems/1475/A.md
          - B. New Year's Number: problems/1475/B.md
      - 1974:
          - A. Phone Desktop: problems/1974/A.md
      - 1975:
          - A. Bazoka and Mocha's Array: problems/1975/A.md
          - B. 378QAQ and Mocha's Array: problems/1975/B.md

# https://squidfunk.github.io/mkdocs-material/

theme:
  highlightjs: true
  font:
    text: Roboto
  name: "material"
  language: en
  include_sidebar: true
  #favicon: assets/img/icon.png
  #logo: assets/img/logo.png
  icon:
    repo: fontawesome/brands/git-alt
  feature:
    tabs: true
  #   palette:
  #     primary: "indigo"
  #     accent: "deep orange"
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: "black"
      accent: "orange"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  i18n:
    prev: "Previous"
    next: "Next"
  features:
    - navigation.sections
    - navigation.instant

copyright: "Copyright &copy; 2024 Girish Thatte"

extra_css:
  - stylesheets/extra.css
    # - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  #     - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/
  #     - assets/js/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - tags:
      tags_file: tags.md

# https://squidfunk.github.io/mkdocs-material/extensions/
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  - footnotes
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.mark # highlight text
  - pymdownx.highlight:
      use_pygments: true # hljs is used instead of pygment for TOML highlighting support
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  disqus: "codeforces-solutions"
