name: Codeforces solutions using MkDocs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Codeforces Solutions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Main
              uses: actions/checkout@v2

            - name: Set up Python 3.12
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12"
                  architecture: x64

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt

            - name: Deploy
              run: |
                  git pull
                  cd codeforces-solutions
                  mkdocs gh-deploy --force
